### ISSUE TITLE
multiple symbols in option 

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/huobi_futures_Python#43]
In option strategy(gamma scalping, straddle,...) , multiple options are required to synthesize
position.  Is there **simpler way to obtain**
self.trader = Trade(**cc) and self.market = Market(**cc)
for **multiple options.**

Currently your config.json and stategy.py are extended as
After extending "Market" in config.json as 

    "MARKETS": [
        {
            "platform": "huobi_option",
            "symbol": "ETH-USDT-201023-C-380",
            "channels":[
                "orderbook", "kline", "trade"
            ],
            "orderbook_length": 10,
            "orderbooks_length": 100,
            "klines_length": 100,
            "trades_length": 100,
            "wss": "wss://api.hbdm.vn"

        },
        {
            "platform": "huobi_swap",
            "symbol": "ETH-USD",
            "contract_type": "SWAP",
            "channels":[
                "orderbook", "kline", "trade"
            ],
            "orderbook_length": 10,
            "orderbooks_length": 100,
            "klines_length": 100,
            "trades_length": 100,
            "wss": "wss://api.hbdm.vn"

        },
        {
            "platform": "huobi_option",
            "symbol": "ETH-USDT-201023-P-380",
            "channels":[
                "orderbook", "kline", "trade"
            ],
            "orderbook_length": 10,
            "orderbooks_length": 100,
            "klines_length": 100,
            "trades_length": 100,
            "wss": "wss://api.hbdm.vn"

        }
		
strategy.py is extended to handle both call and put as

        _self.strategy2 = config.strategy
        self.platform2 = config.accounts[2]["platform"]
        self.account2 = config.accounts[2]["account"]
        self.access_key2 = config.accounts[2]["access_key"]
        self.secret_key2 = config.accounts[2]["secret_key"]
        self.host2 = config.accounts[2]["host"]
        self.wss2 = config.accounts[2]["wss"] 
		
	self.symbol2 = config.markets[2]["symbol"]
        self.channels2 = config.markets[2]["channels"]
        self.orderbook_length2 = config.markets[2]["orderbook_length"]
        self.orderbooks_length2 = config.markets[2]["orderbooks_length"]
        self.klines_length2 = config.markets[2]["klines_length"]
        self.trades_length2 = config.markets[2]["trades_length"]
		
        self.market_wss2 = config.markets[2]["wss"]_       
		
		
		        cc2 = {
            "strategy": self.strategy2,
            "platform": self.platform2,
            "symbol": self.symbol2,
            "account": self.account2,
            "access_key": self.access_key2,
            "secret_key": self.secret_key2,
            "host": self.host2,
            "wss": self.wss2,
            "order_update_callback": self.on_event_order_update,
            "asset_update_callback": self.on_event_asset_update,
            "position_update_callback": self.on_event_position_update,
            "init_success_callback": self.on_event_init_success_callback,
        }
        self.trader2 = Trade(**cc2)        

        market_cc2 = {
            "platform": self.platform2,
            "symbols": [self.symbol2],
            "channels": self.channels2,
            "orderbook_length": self.orderbook_length2,
            "orderbooks_length": self.orderbooks_length2,
            "klines_length": self.klines_length2,
            "trades_length": self.trades_length2,
            "wss": self.market_wss2,
            "orderbook_update_callback": self.on_event_orderbook_update,
            "kline_update_callback": self.on_event_kline_update,
            "trade_update_callback": self.on_event_trade_update
        }
        self.market2 = Market(**market_cc2)    		
Orderbook and trade for call and put are confirmed 
_D [2020-10-18 09:21:37,629] [-] [HuobiOptionMarket] data: {"ch": "market.ETH-USDT-201023-C-380.depth.step6", "ts": 1602980497919, "tick": {"mrid": 79284047, "id": 1602980497, "bids": [[3.56, 20], [3.55, 559], [3.35, 742], [3.15, 679], [3, 1498], [2.96, 937], [2.78, 985], [2.6, 651], [2.44, 779], [2.28, 606], [0.11, 10000], [0.01, 1367]], "asks": [[4.47, 437], [4.72, 505], [4.97, 515], [14.56, 985], [14.75, 963], [14.78, 869], [14.86, 1054], [14.89, 986], [14.93, 968], [14.94, 968], [14.95, 869], [14.96, 986], [14.97, 985], [14.98, 855], [15, 89], [999, 936]], "ts": 1602980497917, "version": 1602980497, "ch": "market.ETH-USDT-201023-C-380.depth.step6"}}_ 

_D [2020-10-18 09:21:37,631] [-] [HuobiOptionMarket] data: {"ch": "market.ETH-USDT-201023-P-380.trade.detail", "ts": 1602846324315, "tick": {"id": 76376723, "ts": 1602846324295, "data": [{"amount": 1010, "ts": 1602846324295, "id": 763767230000, "price": 17.91, "direction": "sell"}, {"amount": 190, "ts": 1602846324295, "id": 763767230001, "price": 17.73, "direction": "sell"}]}}_
as in on_event_trade_update and on_event_orderbook_update.

Best regards,
Ingyu

**Comment by foonsun** [comment]
Hi,Ingyu. You can also follow the guide below to handle the multpile options,however, you have to handle the data properly.


```python
def initialize():
    from .strategy.option_arbitrage import OptionStrategy
    for market in config.MARKETS:
        OptionStrategy(**market)
```

**Comment by igkoh** [comment]
****

**Comment by igkoh** [comment]
Dear Foonsun,

  Partial improvment using your guideline of ** in list of variable length dictionary config.MARKETS
in strategy.py simplifies the code as:  
		for market in config.MARKETS:
            
            cc = {
                "platform": self.platform,
                "symbols": [self.symbol],
                "channels": self.channels,
                "orderbook_length": self.orderbook_length,
                "orderbooks_length": self.orderbooks_length,
                "klines_length": self.klines_length,
                "trades_length": self.trades_length,
                "wss": self.market_wss,
                "orderbook_update_callback": self.on_event_orderbook_update,
                "kline_update_callback": self.on_event_kline_update,
                "trade_update_callback": self.on_event_trade_update
            }
            self.market = Market(**cc)       


In orderbook_update, branch on multiple options is executed into multiple option as :

orderbook
{"platform": "huobi_option", "symbol": "ETH-USDT-201023-C-350", "asks": [["33.51000000", "740.00000000"], ["33.79000000", "713.00000000"], ["34.09000000", "695.00000000"], ["34.40000000", "623.00000000"], ["34.73000000", "569.00000000"], ["35.07000000", "597.00000000"], ["35.43000000", "551.00000000"], ["35.80000000", "580.00000000"]], "bids": [["17.95000000", "486.00000000"], ["16.15000000", "83.00000000"], ["15.67000000", "2.00000000"], ["14.53000000", "881.00000000"], ["13.08000000", "817.00000000"], ["11.77000000", "857.00000000"], ["10.59000000", "555.00000000"], ["9.53000000", "706.00000000"], ["8.58000000", "973.00000000"], ["0.01000000", "9000.00000000"]], "timestamp": 1603260060625}
orderbook
{"platform": "huobi_option", "symbol": "ETH-USDT-201023-C-380", "asks": [["5.50000000", "881.00000000"], ["6.09000000", "508.00000000"], ["6.27000000", "502.00000000"], ["6.46000000", "551.00000000"], ["6.66000000", "335.00000000"], ["8.12000000", "206.00000000"], ["15.00000000", "410.00000000"], ["20.00000000", "525.00000000"], ["36.00000000", "534.00000000"], ["98.88000000", "1838.00000000"]], "bids": [["4.88000000", "962.00000000"], ["4.73000000", "883.00000000"], ["4.59000000", "692.00000000"], ["4.45000000", "918.00000000"], ["4.31000000", "645.00000000"], ["4.18000000", "608.00000000"], ["4.06000000", "527.00000000"], ["3.93000000", "968.00000000"], ["2.00000000", "1000.00000000"], ["1.85000000", "366.00000000"]], "timestamp": 1603260060617}
orderbook
{"platform": "huobi_option", "symbol": "ETH-USDT-201023-P-380", "asks": [["6.10000000", "502.00000000"], ["6.28000000", "6.00000000"], ["6.47000000", "505.00000000"], ["6.66000000", "532.00000000"], ["6.86000000", "527.00000000"], ["7.06000000", "510.00000000"], ["7.27000000", "562.00000000"], ["7.49000000", "501.00000000"]], "bids": [["5.08000000", "513.00000000"], ["4.93000000", "671.00000000"], ["4.78000000", "521.00000000"], ["4.64000000", "206.00000000"], ["4.50000000", "589.00000000"], ["4.37000000", "772.00000000"], ["4.24000000", "933.00000000"], ["4.11000000", "545.00000000"], ["3.00000000", "480.00000000"], ["0.01000000", "25000.00000000"]], "timestamp": 1603260061510}
orderbook
{"platform": "huobi_option", "symbol": "ETH-USDT-201023-P-350", "asks": [["0.93000000", "634.00000000"], [
	
			
			
I appreciate helpful guideline in multiple option.
Best regards,
Ingyu

**Comment by foonsun** [comment]
Thanks for your feedback.
