### ISSUE TITLE
demo跑不起来

### ISSUE THREAD

**Issue by Lxtluck** [hbdmapi/huobi_futures_Python#46]
![image](https://user-images.githubusercontent.com/26915230/102302858-e125e980-3f94-11eb-9c59-95d55352ec35.png)
![image](https://user-images.githubusercontent.com/26915230/102302884-edaa4200-3f94-11eb-8011-b28dbb16cc18.png)

**Comment by Lxtluck** [comment]
usdt永续合约

**Comment by foonsun** [comment]
@Lxtluck 上面的错误是：连接server失败。目前此错误经常出现在国内网络情况下，可以尝试使用"api.btcgateway.pro"或者"api.hbdm.vn"来运行；另外一种是放置在服务器上运行。此种错误目前没有更好的办法

**Comment by Lxtluck** [comment]
![image](https://user-images.githubusercontent.com/26915230/102317200-1c82e100-3fb2-11eb-8eac-c11a279b2592.png)
还是这样

**Comment by foonsun** [comment]
> ![image](https://user-images.githubusercontent.com/26915230/102317200-1c82e100-3fb2-11eb-8eac-c11a279b2592.png)
> 还是这样

本地测试连接正常，每个地区的网络不可控，上面仍然是本地网络不稳定导致一直无法连接，建议在服务器上来运行该程序看是否可行。

**Comment by Lxtluck** [comment]
![image](https://user-images.githubusercontent.com/26915230/102459677-dfd1eb00-4080-11eb-8ca9-a652c37ba0bf.png)
api.hbdm.vn 我是可以ping通的
