### ISSUE TITLE
huobi_swap demo 如何获取实时的Kline行情数据中的‘open’值

### ISSUE THREAD

**Issue by 18728476237** [hbdmapi/huobi_futures_Python#50]
你好。我直接运行你的huobi_swap DEMO,控制台实时打印了三种类型的信息：
[2021-02-05 09:08:51,968] [-] [MyStrategy] orderbook: {"platform": "huobi_swap", "symbol": "BTC-USD", "asks": [["37181.40000000", "2997.00000000"], ["37181.50000000", "7.00000000"],
D [2021-02-05 09:08:52,004] [-] [HuobiSwapMarket] data: {"ch": "market.BTC-USD.depth.step6", "ts": 1612487411159, "tick": {"mrid": 73870283258, "id": 1612487411, "bids": [[37181.3, 3845], [37181.2, 1],
D [2021-02-05 09:08:52,004] [-] [HuobiSwapMarket] symbol: BTC-USD orderbook: {"platform": "huobi_swap", "symbol": "BTC-USD", "asks": [["37181.40000000", "3999.00000000"],
我想只打印kline实时行情，而不是打印前面的3中类型的实时信息，我应该修改哪个函数。你前一封邮件说的logger.info()我确实看不懂怎么就打印了前述3种实时信息，谢谢

**Comment by foonsun** [comment]
目前默认是1MIN K线；

1、配置config.json里kline为订阅kline 1MIN：https://github.com/hbdmapi/huobi_futures_Python/blob/master/examples/huobi_swap/config.json#L25

2、Kline打印在这里：https://github.com/hbdmapi/huobi_futures_Python/blob/master/examples/huobi_usdt_swap/strategy.py#L183
有kline数据就会在这里打印每次推送的kline。
https://github.com/hbdmapi/huobi_futures_Python/blob/master/examples/huobi_swap/strategy.py#L182

**Comment by 18728476237** [comment]
非常感谢回复如此及时。
我大概没有说清楚我最重要的问题。
我重新理下我的思路。
对于huobi_swap demo main.py 中除了初始化quant.initialize(config_file)  initialize()外，就是quant.start()；
跳转到quant.py, start()方法最核心的功能语句是 self.loop.run_forever() ；而run_forever() 是python实现的函数，不是我们自己写的函数，
那我要定义一个变量close 来接收每条Kline数据的'close'值（这个值是随时跟下一个close值比较，大于1个usdt就更新，所以不用list），
我在哪里初始化这个close变量呢？在main.py中？还是那其它哪个文件的全局，还是哪个类中？
谢谢
