### ISSUE TITLE
如何通过huobi_swap demo下单

### ISSUE THREAD

**Issue by 18728476237** [hbdmapi/huobi_futures_Python#52]
新春快乐！
我通过Kline获取到实时的close数据，然后我设置close到达某个值时，进行买入多或者空的操作，应该调用哪个函数来实现这个逻辑？进一步来说，是调用huobi_swap_markey.py中的process_trade(self, data)来实现吗？这个函数感觉只是在打印实时的交易数据呢？谢谢！

**Comment by ad-long** [comment]
可以参考这个:alpha/platforms/huobi_usdt_swap_cross_trade.py
line 385: result, error = await self._rest_api.create_orders({"orders_data": orders_data})

**Comment by foonsun** [comment]
参考这里的批量下单函数就可以：https://github.com/hbdmapi/huobi_futures_Python/blob/master/examples/huobi_swap/strategy.py#L148

**Comment by 18728476237** [comment]
我在python demo项目的example/huobi_swap/strategy.py的on_event_kline_update(self, kline: Kline)函数中引用 alpha/platforms/huobi_swap_trade.py中的create_order()函数如下：action = ORDER_ACTION_BUY
            price = 41000.1
            quantity = 100
            direction = "buy"
            offset = "open"
            lever_rate = 20
            order_price_type = "optimal_20"
            client_order_id = None
            symbol = "BTC-USD"
            result, error = await HuobiSwapTrade.create_order(self, action, symbol ,price,
                                                                        quantity, direction, offset,
                                                                        lever_rate, order_price_type,
                                                                        client_order_id)

            print("新订单返回的result:%s,error:%s" % (result, error))
打印result和error：result:None,error:order type error

**Comment by 18728476237** [comment]
如果改变函数传参如下： 
            order_type = ORDER_TYPE_MARKET
            action = ORDER_ACTION_BUY
            price = 41000.1
            quantity = 100
            direction = "buy"
            offset = "open"
            lever_rate = 20
            order_price_type = "optimal_20"
            client_order_id = None
            symbol = "BTC-USD"
            result, error = await HuobiSwapTrade.create_order(HuobiSwapTrade,action, price, quantity, order_type,
                                                              client_order_id,symbol ,price,direction,
                                                              offset,lever_rate, order_price_type)
            print("新订单返回的result:%s,error:%s" % (result, error))
则打印：AttributeError: type object 'HuobiSwapTrade' has no attribute '_rest_api'

**Comment by foonsun** [comment]
async def create_order(self, contract_code, price, quantity, direction, offset, lever_rate,
                           order_price_type, client_order_id=None):

需要根据以上方法来填参，如下例子调用：

order_nos, error = await self.trader._rest_api.create_order(“BTC-USD”, price, quantity, direction, offset, lever_rate, order_price_type, client_order_id)
if error:
           logger.error(self.strategy, "create future order error! error:", error, caller=self)
else: 
          logger.info(self.strategy, "create future orders success:", order_nos, caller=self)

**Comment by foonsun** [comment]
HuobiSwapTrade 需要先根据例子的__init__ 先做实例化，才能调用。

**Comment by 18728476237** [comment]
async def create_order(self, contract_code, price, quantity, direction, offset, lever_rate,
order_price_type, client_order_id=None):


这个函数定义在哪个文件里边？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hbdmapi/huobi_futures_Python"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月15日(星期一) 下午3:26
收件人:&nbsp;"hbdmapi/huobi_futures_Python"<huobi_futures_Python@noreply.github.com&gt;;
抄送:&nbsp;"宇"<525082270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hbdmapi/huobi_futures_Python] 如何通过huobi_swap demo下单 (#52)





 
async def create_order(self, contract_code, price, quantity, direction, offset, lever_rate,
 order_price_type, client_order_id=None):
 
需要根据以上方法来填参，如下例子调用：
 
order_nos, error = await self.trader._rest_api.create_order(“BTC-USD”, price, quantity, direction, offset, lever_rate, order_price_type, client_order_id)
 if error:
 logger.error(self.strategy, "create future order error! error:", error, caller=self)
 else:
 logger.info(self.strategy, "create future orders success:", order_nos, caller=self)

**Comment by foonsun** [comment]
https://github.com/hbdmapi/huobi_futures_Python/blob/master/alpha/platforms/huobi_swap_api.py#L175

**Comment by 18728476237** [comment]
你上一封邮件写到：
order_nos, error = await self.trader._rest_api.create_order(“BTC-USD”, price, quantity, direction, offset, lever_rate, order_price_type, client_order_id)
我在example/huobi_swap/strategy.py中先import HuobiSwapRestAPI 类，然后原样调用上面这个函数，报错：
AttributeError: 'Trade' object has no attribute '_rest_api'


await 后面的 self.trader._rest_api. 是什么意思？create_order（）这个函数不是类HuobiSwapRestAPI的一个方法吗？
我改成order_nos, error = await&nbsp;&nbsp;HuobiSwapRestAPI.create_order(“BTC-USD”, price, quantity, direction, offset, lever_rate, order_price_type, client_order_id)却仍然报错：
File "/tmp/pycharm_project_13/alpha/platforms/huobi_swap_api.py", line 204, in create_order
&nbsp; &nbsp; success, error = await self.request("POST", uri, body=body, auth=True)
AttributeError: 'str' object has no attribute 'request'



谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hbdmapi/huobi_futures_Python"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月15日(星期一) 下午3:26
收件人:&nbsp;"hbdmapi/huobi_futures_Python"<huobi_futures_Python@noreply.github.com&gt;;
抄送:&nbsp;"宇"<525082270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hbdmapi/huobi_futures_Python] 如何通过huobi_swap demo下单 (#52)





 
async def create_order(self, contract_code, price, quantity, direction, offset, lever_rate,
 order_price_type, client_order_id=None):
 
需要根据以上方法来填参，如下例子调用：
 
order_nos, error = await self.trader._rest_api.create_order(“BTC-USD”, price, quantity, direction, offset, lever_rate, order_price_type, client_order_id)
 if error:
 logger.error(self.strategy, "create future order error! error:", error, caller=self)
 else:
 logger.info(self.strategy, "create future orders success:", order_nos, caller=self)

**Comment by 18728476237** [comment]
order_nos, error = await self.trader._rest_api.create_order(“BTC-USD”, price, quantity, direction, offset, lever_rate, order_price_type, client_order_id)
我在example/huobi_swap/strategy.py中先import HuobiSwapRestAPI 类，然后原样调用上面这个函数，报错：
AttributeError: 'Trade' object has no attribute '_rest_api'

await 后面的 self.trader._rest_api. 是什么意思？create_order（）这个函数不是类HuobiSwapRestAPI的一个方法吗？
我改成order_nos, error = await  HuobiSwapRestAPI.create_order(“BTC-USD”, price, quantity, direction, offset, lever_rate, order_price_type, client_order_id)却仍然报错：
File "/tmp/pycharm_project_13/alpha/platforms/huobi_swap_api.py", line 204, in create_order
    success, error = await self.request("POST", uri, body=body, auth=True)
AttributeError: 'str' object has no attribute 'request'
