### ISSUE TITLE
details wanted

### ISSUE THREAD

**Issue by Sinever** [hbdmapi/huobi_futures_Python#54]
how could I get data details, including but not limited to market, trade and kline.
for example:
![image](https://user-images.githubusercontent.com/33723964/108225450-e9f29180-7176-11eb-8a87-e71db0fd70b6.png)
what do the fields amount, quantity, trade_turnover, ts, id mean.
and so do they.
    "MARKETS": [
        {
            "platform": "huobi_usdt_swap",
            "channels":[
                "orderbook", "kline", "trade"
            ],
            "orderbook_length": 10,
            "orderbooks_length": 1000,
            "klines_length": 10,
            "trades_length": 1000,
            "wss": "wss://api.hbdm.vn"

        }
    ],
thank you.

**Comment by foonsun** [comment]
Dear Sinever,

1、

The example above with the websocket topic: market.BTC-USDT.trade.detail  has been integrated just as "trade" in config.json: 

https://github.com/hbdmapi/huobi_futures_Python/blob/master/examples/huobi_usdt_swap/config.json#L25

```
"MARKETS": [
{
"platform": "huobi_usdt_swap",
"channels":[
"orderbook", "kline", "trade"
],
"orderbook_length": 10,
"orderbooks_length": 1000,
"klines_length": 10,
"trades_length": 1000,
"wss": "wss://api.hbdm.vn"

    }
]
```

2、

amount field means quantity(Cont.),Sum of both buy and sell sides. such as 200,2000,etc.

quantity field means quantity in coin.

turnover filed means trade turnover(quoted currency).

ts field means trade timestamp.

id field means unique transaction Id(symbol level).

3、

channels means the data need to subscribe. 

such as kline means the kline subscription of 1MIN kline, 

 orderbook means the 20 level orderbook subscription, 

trade means the market trade detail subscription.

The length means that the max size of the data to be stored.

Thanks.
