### ISSUE TITLE
more docs wanted

### ISSUE THREAD

**Issue by Sinever** [hbdmapi/huobi_futures_Python#55]
very respectful for your answer in issue https://github.com/hbdmapi/huobi_futures_Python/issues/54.
but, what i want is more details about our platform, rather than only the examples in the issue.
if i need to know the meaning of more parameters, i need to ask one by one in more issues?

**Comment by Sinever** [comment]
by the way, how i get more trade-pairs data in one program for example getting USDT-BTC, USDT-ETH and USDT-DOT in one thread or process.
Is it available to initialize more Market(**cc) and Trade(**cc) instances use different trade-pairs?

**Comment by foonsun** [comment]
Hi, Sinever, more docs will be preprared.

More trade-pairs data needs be to configed in the config.json.

 It's not available to initilaize more Market(**cc) or Trade(**cc) instances.

Different instances can share the data through global variable.
