### ISSUE TITLE
open interest in futures and swaps

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/huobi_futures_Python#58]
Open interest and liquidation are  important features in trading.  
Currently open interest is received in async def on_event_kline_update as
response=requests.get(self.OIurl)
with OIurl as '_https://futures.huobi.com//api/v1/contract_open_interest_'.
Then response.json()['data'] of 'symbol'=='ETH' and 'contract_type'=='quarter' gives open interest
as 'volume'.
Direct url call in on_event ... causes significant time delay as a whole.

**Question 1:**  How can I solve this problem of time delay due to direct access requests?
One solurion is a separate program getting open interest and sending through online database
like MQRabbit or redis.

**Question 2**:  What is fast response for open interest in swaps?
Url with "_https://futures.huobi.com///linear-swap-api/v1/swap_open_interest_" gives response.json()['data'] as in futures case.  Async/await low latency way of getting open interest in swaps would be extremely helpful.

**Question 3**:Liquidation in futures and swaps is other important features.  **What is url address for liquidation**? Url "_https://futures.huobi.com//api//v1/contract_liquidation_orders_"  
"_https://futures.huobi.com//swap-api/v1/swap_liquidation_orders_" do not succeed with bad request 400. How can I get low latency liquidation data?

**Question 4**: Is it faster by using http_utils __alpha.platforms.huobi_usdt_swap.http_utils import_ *_?

Best regards,
Ingyu

**Comment by ad-long** [comment]
'https://futures.huobi.com//api/v1/contract_open_interest'.
should be:
 'https://api.hbdm.com/api/v1/contract_open_interest'.

**Comment by ad-long** [comment]
more about server url host address to see: https://docs.huobigroup.com/docs/dm/v1/en/#address
"Question 4"---> no, http_utils _alpha.platforms.huobi_usdt_swap just is a package for "full usdt swap api".
