### ISSUE TITLE
请求kline数据，返回的数据是空的

### ISSUE THREAD

**Issue by ckelsel** [hbdmapi/huobi_futures_Python#61]
发送的样例是官方文档的例子
https://docs.huobigroup.com/docs/usdt_swap/v1/cn/#kline-2

    {
    "req": "market.BTC-USDT.kline.1min",
    "id": "id4",
    "from": 1579247342,
    "to": 1579247342
    }

返回

{'id': 'id4', 'rep': 'market.BTC-USDT.kline.1min', 'ts': 1616852393455, 'wsid': 184392393, 'status': 'ok', 'data': []}

这是代码写错了，还是哪里出问题？

**Comment by foonsun** [comment]
USDT本位合约是2020 10月份上线。上面数据空，是因为时间戳是2020的，建议修改后再重试就可以。
