### ISSUE TITLE
昨天行情波动巨大时下单接口调用失败

### ISSUE THREAD

**Issue by 18728476237** [hbdmapi/huobi_futures_Python#63]
昨天行情波动巨大的上午11：00前后，用demo的http_utils.py中的逐仓下单接口下单3次，每次间隔5分钟以上，全部失败，此前和 昨天中午1：00以后都是正常的。调用的函数 如下
post(access_key: str, secret_key: str, host: str, path: str, data: dict = None) -> json
报错都是一样的：
"status": "error", "err_code": 1067, "err_msg": "The volume field is illegal. Please re-enter."

**Comment by ad-long** [comment]
麻烦贴一下当时 post(access_key: str, secret_key: str, host: str, path: str, data: dict = None) 中 data 的参数值. 可能是volume 缺失或者 类型 不对
