### ISSUE TITLE
分钟级别的k线是否有当前k线是否结束的标志?

### ISSUE THREAD

**Issue by tianhm** [hbdmapi/huobi_futures_Python#65]
需要k线结束的时候触发计算,现在用k线间隔整除的方法有信号漂移.

**Comment by foonsun** [comment]
分钟级别的K线结束，比较简单的参考方式是看Kline ID，如果Kline ID 跳到下一个分钟时间戳，前一分钟的数据就是结束数据。

**Comment by tianhm** [comment]
订阅返回的数据中 没有kline ID, 这个id如何获取到呢?

close = {str} '2514.16000000'
data = {dict: 9} {'platform': 'huobi_usdt_swap_cross', 'symbol': 'ETH-USDT', 'open': '2513.21000000', 'high': '2516.19000000', 'low': '2513.21000000', 'close': '2514.16000000', 'volume': '1400.88000000', 'timestamp': 1623223668417, 'kline_type': 'kline'}
high = {str} '2516.19000000'
kline_type = {str} 'kline'
low = {str} '2513.21000000'
open = {str} '2513.21000000'
platform = {str} 'huobi_usdt_swap_cross'
symbol = {str} 'ETH-USDT'
timestamp = {int} 1623223668417
volume = {str} '1400.88000000'

**Comment by tianhm** [comment]
我用的是 huobi_usdt_swap_cross 下面的程序.

**Comment by foonsun** [comment]
目前订阅的K线还没有KID，后续版本会加上这个标示

**Comment by tianhm** [comment]
谢谢,希望尽快搞定啊.
