### ISSUE TITLE
how to get all option tickers ?

### ISSUE THREAD

**Issue by Mike1999aa** [hbdmapi/huobi_futures_Python#66]
how to get all option tickers in huobi?

market_client = HuobiOptionRestAPI(host = 'https://api.hbdm.com', access_key = apiKey, secret_key = secret)
market_client.get_option_info()

Output: <coroutine object HuobiOptionRestAPI.get_option_info at 0x00000225A700D620>

Also, could you add some examples for us to use?

many thanks in advance!

**Comment by foonsun** [comment]
Dear Mike, Huobi Option has been offline. Sorry for any inconvince. 

await is needed to excute the coroutine object.such as:

market_client = HuobiOptionRestAPI(host = 'https://api.hbdm.com', access_key = apiKey, secret_key = secret)
await market_client.get_option_info()
