### ISSUE TITLE
Submit a market order for derivatives

### ISSUE THREAD

**Issue by davidebaldini** [hbdmapi/huobi_futures_Python#67]
The API documentation for Huobi's perpetual swaps and for derivatives doesn't include _market orders_ among the order types supported by Huobi. I contacted Huobi's customer care and they confirmed that Huobi's derivatives only permit _limit orders_, and to achieve _market execution_ it is required to submit a _limit order_ with its price set across the spread and with the option "post-only" disabled.

This artefice easily becomes fragile over their API, causing the risk to submit a _limit order_ in place of a _market order_ if the instrument's price fluctuates rapidly and if the price of the submitted _limit order_ doesn't happen to be still across the spread by the time the order reaches the matching engine, after some possible network delay or internal latency.

Is this correct?
What best practices do you suggest to achieve _market execution_ on Huobi's derivatives?

**Comment by foonsun** [comment]
@davidebaldini Hi, sorry for my late response.yeah,it is correct. "market" orders are not existed among the huobi derivatives.
If you want to achieve market execution on Huobi's derivatives, we suggest to use the "optimal_20" type, it means place the order at the best 20 level price. the doc is here:https://huobiapi.github.io/docs/usdt_swap/v1/en/#cross-place-an-order
