### ISSUE TITLE
怎么开单以及查看现在挂单情况 

### ISSUE THREAD

**Issue by ZhuangLii** [hbdmapi/huobi_futures_Python#69]
如题，第一次用，希望指教一下

**Comment by iohannes-long** [comment]
可以参考:
https://github.com/hbdmapi/huobi_futures_Python/blob/a505cfef0591d4adc610b7ef11bd06cb2d2ae2a5/examples/huobi_future/strategy.py#L129
async def place_orders(self):

最终调用:
https://github.com/hbdmapi/huobi_futures_Python/blob/a505cfef0591d4adc610b7ef11bd06cb2d2ae2a5/alpha/platforms/huobi_future_api.py#L247
def get_orderbook(self, symbol):

**Comment by ZhuangLii** [comment]
谢谢
