### ISSUE TITLE
请问如何同时更新多个币种的kline 到 mongodb

### ISSUE THREAD

**Issue by ZhuangLii** [hbdmapi/huobi_futures_Python#70]
请问如何通过调用，on_event_kline_update同时更新多个币种的kline

**Comment by iohannes-long** [comment]
cc = {
            "platform": self.platform,
            "symbols": [self.symbol], # 只能是同一种合约的不同币种, 如usdt永续的不同币种: ['btc-usdt', 'eth-usdt']
            "channels": self.channels,
            "orderbook_length": self.orderbook_length,
            "orderbooks_length": self.orderbooks_length,
            "klines_length": self.klines_length,
            "trades_length": self.trades_length,
            "wss": self.market_wss,
            "orderbook_update_callback": self.on_event_orderbook_update,
            "kline_update_callback": self.on_event_kline_update,
            "trade_update_callback": self.on_event_trade_update
        }

**Comment by ZhuangLii** [comment]
thx
